<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AssetStudio\AssetStudio.csproj" />
    <ProjectReference Include="..\AssetStudioUtility\AssetStudioUtility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.0.0.9375" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AssetStudio.AppCore</RootNamespace>
  </PropertyGroup>

</Project>
